## 使用NumPy进行数据计算

In [1]:
import numpy as np

#### 作业题目中需要用到的数组

In [2]:
np.random.seed(1)
a1 = np.arange(10)
a2 = np.array([1,5,7,4,3])
a3 = np.arange(20).reshape(4,-1)
a4 = np.random.uniform(10,20,50)
a5 = np.random.randint(0,5,10)
a6 = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a7 = np.random.randint(1,4,size = 6)
a8 = np.random.randint(20,size = [2,6])
b1 = np.arange(10).reshape(2,-1)
b2 = np.repeat(1,10).reshape(2,-1)
b3 = np.array(
[np.arange(3),
np.arange(3,6),
np.arange(6,9)])
b4 = np.array([1,2,3,4])
b5 = np.array([5,6,7,8])

#### 例题以及答案格式

In [3]:
# Q.创建一个3×3的所有值为True的numpy数组
# A:
out = np.ones((3,3),dtype = bool)
out   #运行之后可以直接看到结果

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 作业共25道，Q为题目序号，A为答案序号，请阅读题目后在A下作答，不要删除题目中的np.random.seed

##### Q1.将a1转换为2行的2维数组 *注：答案中只明确是2行，系统自动确定列数(★☆☆)

In [21]:
# A1:
a1=a1.reshape(2,-1)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Q2.创建一个10*10的随机数组，并找到这个数组中的最大值、最小值和平均值(★☆☆)

In [12]:
# A2:
ramarr1=np.random.rand(10,10)
ramarr1,ramarr1.max(),ramarr1.min(),ramarr1.mean()

(array([[0.44798018, 0.89213587, 0.37758434, 0.53842469, 0.65229888,
         0.36126102, 0.57100856, 0.63783648, 0.12631489, 0.69020459],
        [0.6477494 , 0.35393909, 0.76323305, 0.35653172, 0.75278835,
         0.88134183, 0.01166919, 0.49810907, 0.07379201, 0.78695147],
        [0.06406733, 0.35531036, 0.94183695, 0.37980329, 0.76292007,
         0.771595  , 0.3013605 , 0.77273915, 0.15292982, 0.57863393],
        [0.009008  , 0.70904252, 0.47064081, 0.76459257, 0.46739268,
         0.26900105, 0.83169259, 0.55132494, 0.0700815 , 0.47247504],
        [0.74276483, 0.19195608, 0.4643115 , 0.23036281, 0.50824754,
         0.20856831, 0.04930424, 0.51886188, 0.17227835, 0.39631329],
        [0.1073653 , 0.50981028, 0.10213523, 0.28871783, 0.23175846,
         0.96766793, 0.27831884, 0.23362252, 0.09155644, 0.57006666],
        [0.41792654, 0.36784324, 0.81299497, 0.28976   , 0.7173916 ,
         0.61294809, 0.42690983, 0.75187297, 0.42781263, 0.42838241],
        [0.36190444, 0.1533

##### Q3.创建一个随机5*5矩阵并对它进行归一化（减去平均值再除以方差）(★☆☆)

In [13]:
#A3:
ramarr2=np.random.rand(5,5)
mean2=ramarr2.mean()
ramarr2-=mean2
var2=ramarr2.var()
ramarr2/=var2
ramarr2


array([[-3.81199032, -3.36341702,  1.0708441 , -2.51242535,  6.05394181],
       [ 0.50077163, -3.53168356,  4.193452  , -2.54807711, -4.24077274],
       [-3.98210691, -3.16572419, -0.79114881, -3.9834691 , -3.3972738 ],
       [ 6.23203335,  1.89956328,  5.11517151,  2.47051184, -1.18165296],
       [ 3.75058371,  1.2413405 ,  3.85815109, -3.1266006 ,  3.24997764]])

##### Q4.删除a1中所包含的a2的元素(★☆☆)

In [19]:
# A4：
mask=~np.isin(a1,a2)
a1=a1[mask]
a1


array([0, 2, 6, 8, 9])

##### Q5.提取a1中的所有奇数为新的数组，并使得a1不发生改变(★☆☆)

In [33]:
# A5:
newa1=a1[a1%2!=0]
newa1

# def f(x):
#     return x%2!=0
# newa1=a1[list(map(f,a1))]
# newa1

array([1, 3, 5, 7, 9])

##### Q6.交换数组a3中的第一行和第3行，第二列和最后一列(★☆☆)

In [55]:
# A6：
tem1=a3[[2,1,0,3],:]
tem1=tem1[:,[0,4,2,3,1]]
tem1

array([[10, 14, 12, 13, 11],
       [ 5,  9,  7,  8,  6],
       [ 0,  4,  2,  3,  1],
       [15, 19, 17, 18, 16]])

##### Q7.(1)反转a3的行 （2）反转a3的列(★☆☆)

In [60]:
# A7：
# [[15 16 17 18 19]
#  [10 11 12 13 14]
#  [ 5  6  7  8  9]
#  [ 0  1  2  3  4]]

# [[ 4  3  2  1  0]
#  [ 9  8  7  6  5]
#  [14 13 12 11 10]
#  [19 18 17 16 15]]
tem2=a3[::-1,:]
tem3=a3[:,::-1]
tem2,tem3


(array([[15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]]),
 array([[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15]]))

##### Q8.在b1的周围加一个全部为0的边框(★★☆)

In [39]:
# A8：


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 4, 0],
       [0, 5, 6, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0, 0]])

##### Q9.创建一个5*5的矩阵，值“1，2，3，4”在此矩阵对角线的正上方(★★☆)

In [44]:
# A9：


array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

##### Q10.从数组a3中提取7到16之间的所有元素，包括7和16(★★☆)

In [45]:
# A10:


array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

##### Q11.创建一个4*6的二维数组，包含10~20之间的浮点数，并保留三位小数(★★☆)

In [49]:
#A11：


array([[14.725, 17.428, 11.92 , 14.643, 12.304, 15.082],
       [12.086, 10.493, 15.189, 11.723, 13.963, 11.074],
       [15.098, 11.021, 12.887, 12.318, 19.677, 12.783],
       [12.336, 10.916, 15.701, 14.179, 13.678, 18.13 ]])

##### Q12.将b3转换为一维数组(★★☆)

In [58]:
# A12：


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Q13.获取a4中前五个最大的值(★★☆)

In [61]:
# A13：


array([ 2, 38, 14, 27, 26], dtype=int64)

##### Q14.计算b4和b5之间的欧式距离(★★☆)

In [62]:
# A14:


8.0

##### Q15:找出a5中重复的元素并标记为True（如果元素第一次出现则标记为False） (★★★)

In [68]:
a5

array([1, 3, 0, 0, 2, 2, 1, 3, 4, 2])

In [69]:
# A15：


array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

##### Q16:给出下列A和B，求解2Ax = B(★★★)

In [71]:
A = np.array([[1,2,3],[-1,-3,-9],[2,2,8]])
B = np.array([12,15,8])
# A16：


array([10.5,  1.5, -2.5])

##### Q17:筛选iris_2d中同时满足行petallength (3rd column) > 1.5sepallength (1st column) < 5.0的项目

In [74]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#A17：


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

##### Q18:对数组a8中各项目进行排名，数值越小排名越高，如果存在并列情况，在a8中位置越靠前则排名越高。
##### 例：[1,3,4,5,4,1]——————排名为：[0,2,3,5,4,1]

In [83]:
# A18:


array([[4, 1, 0, 5, 2, 3],
       [0, 4, 3, 1, 5, 2]], dtype=int64)

##### Q19:以iris species作为输入，创建不同类别的ID.
##### 如令所有的'Iris-setosa'都为0,所有的'Iris-versicolor'都为1(★★★)

In [89]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url,delimiter = ',',dtype = 'str',usecols = 4)
# A19：


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

##### Q20:创建一个3*10的numpy数组Z
##### 请回答print函数中的代码的功能(★★★)

In [105]:
Z = np.random.randint(0,3,(3,10))

In [106]:
Z

array([[2, 2, 0, 1, 2, 1, 1, 1, 1, 0],
       [1, 2, 1, 0, 0, 2, 2, 1, 0, 0],
       [0, 2, 2, 0, 1, 1, 1, 2, 1, 1]])

In [111]:
(~Z.any(axis=0)).any()

False

In [112]:
~Z.any(axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [102]:
print((~Z.any(axis=0)).any())

False


In [ ]:
# A20：
